#### properties and attribute of numpy array 

# Shape

In [1]:
import numpy as np

In [56]:
nums1=[1,2,3,4,5,6]
nums2=[4,5,6,7,8,9]
arr1= np.array(nums)
arr1

array([1, 2, 3, 4, 5, 6])

In [3]:
arr1.shape

(6,)

In [7]:
arr2=np.array([nums1,nums2])
arr2

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [8]:
arr2.shape

(2, 6)

In [20]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
arr3.shape

(2, 2, 2)

# ndim
ndim is used to check the dimanesion of array

In [22]:
arr3.ndim

3

In [23]:
arr2.ndim

2

In [24]:
arr1.ndim

1

# Size

In [25]:
arr1


array([1, 2, 3, 4, 5, 6])

In [26]:
arr1.size

6

In [27]:
arr2

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [28]:
arr2.size


12

In [40]:
arr3.size

8

# Itemsize
returns the size of the values inside the memory for int it will be 4 for float it will be 8

In [41]:
arr3.itemsize

4

In [44]:
arr=np.array([1,2,3,4],dtype=float)
arr.itemsize

8

# Dtype

In [45]:
arr3.dtype


dtype('int32')

In [46]:
arr.dtype



dtype('float64')


# Astype
used to convert the datatype of ndarray

In [57]:
arr1.dtype

dtype('int32')

In [58]:
arr1

array([1, 2, 3, 4, 5, 6])

In [59]:
arr1.astype(float)

array([1., 2., 3., 4., 5., 6.])

In [60]:
arr1

array([1, 2, 3, 4, 5, 6])