# Numpy; numerical python

numpy is a numerical library in python and is used to working with array, we use numpy array for calculation as it is fast as compared to python list

In [8]:
import numpy as np

In [2]:
# numpy is used to work with array the array object in numpy is ndarray
array =np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [3]:
print(type(array))

<class 'numpy.ndarray'>


## 1-d array


In [14]:
arr1= np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [15]:
#using zeros
arr2 =np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
#using 1's
arr3=np.ones(10)
arr3
print(arr3.shape)

(10,)


In [25]:
# indentity
arr4 = np.identity(1)
arr4

array([[1.]])

In [29]:
# using arange()
arr5=np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2-D array 

#### it is the combination of multiple 1-d array

In [31]:
arr6 = np.array([[1,2,3,4],[5,6,7,8]])
arr6

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr6.shape

(2, 4)

In [12]:
arr7 =np.zeros((2,3))
arr7

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr8=np.identity((5))
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
type(arr8)

numpy.ndarray

In [20]:
arr9 = np.linspace(2,8,10)
arr9

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [21]:
arr10 = np.copy(arr9)
arr10

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])